repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.12.0
    hooks:
      - id: black
        language_version: python3.12

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

-   repo: https://github.com/crate-ci/typos
    rev: v1.40.0
    hooks:
      - id: typos

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies:
        - django-stubs
        - tailwind
        - django_browser_reload
        - sympy
        - django_mathjax

-   repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

-   repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python django/manage.py test
        always_run: true
        pass_filenames: false
        language: system
